name: publish
on: [create]
jobs:
  call-base-workflow:
    uses: ./.github/workflows/base-workflow.yml
  draft-release:
    runs-on: ubuntu-latest
    needs: call-base-workflow
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
  pypi-publish:
    runs-on: ubuntu-latest
    needs: call-base-workflow
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install build --user
      - run: python -m build --sdist --wheel --outdir dist/ .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/
